# Generated by Django 5.2.7 on 2026-01-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte'), ('transfer', 'Virement')], default='cash', max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
    ]
