# Generated by Django 5.2.7 on 2026-01-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte'), ('transfer', 'Virement'), ('mobile_money', 'Mobile Money (MTN/Orange)')], default='cash', max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
    ]
