# Generated by Django 5.2.7 on 2026-01-05 15:12

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(choices=[('super_admin', 'Super Administrateur'), ('manager', 'Gérant/Directeur'), ('store_manager', 'Responsable Point de Vente'), ('warehouse_keeper', 'Magasinier'), ('cashier', 'Caissier'), ('salesperson', 'Vendeur'), ('accountant', 'Comptable'), ('commercial', 'Commercial')], max_length=50, unique=True, verbose_name='Nom du rôle')),
                ('display_name', models.CharField(max_length=100, verbose_name="Nom d'affichage")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Gérer les utilisateurs')),
                ('can_manage_products', models.BooleanField(default=False, verbose_name='Gérer les produits')),
                ('can_view_products', models.BooleanField(default=False, verbose_name='Voir les produits')),
                ('can_manage_categories', models.BooleanField(default=False, verbose_name='Gérer les catégories')),
                ('can_view_categories', models.BooleanField(default=False, verbose_name='Voir les catégories')),
                ('can_manage_services', models.BooleanField(default=False, verbose_name='Gérer les services')),
                ('can_view_services', models.BooleanField(default=False, verbose_name='Voir les services')),
                ('can_manage_inventory', models.BooleanField(default=False, verbose_name='Gérer le stock')),
                ('can_view_inventory', models.BooleanField(default=False, verbose_name='Voir le stock')),
                ('can_manage_sales', models.BooleanField(default=False, verbose_name='Gérer les ventes')),
                ('can_manage_customers', models.BooleanField(default=False, verbose_name='Gérer les clients')),
                ('can_manage_suppliers', models.BooleanField(default=False, verbose_name='Gérer les fournisseurs')),
                ('can_manage_cashbox', models.BooleanField(default=False, verbose_name='Gérer la caisse')),
                ('can_manage_loans', models.BooleanField(default=False, verbose_name='Gérer les emprunts')),
                ('can_manage_expenses', models.BooleanField(default=False, verbose_name='Gérer les dépenses')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='Voir les analytics')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='Exporter les données')),
                ('access_scope', models.CharField(choices=[('all', 'Tous les points de vente'), ('assigned', 'Points de vente assignés uniquement'), ('own', 'Propres données uniquement')], default='assigned', max_length=20, verbose_name="Périmètre d'accès")),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user_type', models.CharField(default='collaborator', editable=False, max_length=20, verbose_name="Type d'utilisateur")),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+237612345678'. 9 à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Photo de profil')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule employé')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('alternative_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+237612345678'. 9 à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone alternatif')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name="Contact d'urgence")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+237612345678'. 9 à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name="Téléphone du contact d'urgence")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='tenant_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='tenant_user_set', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='Rôle principal')),
                ('secondary_roles', models.ManyToManyField(blank=True, related_name='secondary_users', to='accounts.role', verbose_name='Rôles secondaires')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('print', 'Impression')], max_length=20, verbose_name='Action')),
                ('module', models.CharField(max_length=50, verbose_name='Module')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name="Type d'objet")),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clé de session')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Heure de connexion')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de déconnexion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateurs',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('type', models.CharField(choices=[('stock_rupture', 'Rupture de stock'), ('stock_low', 'Stock faible'), ('debt_due', 'Échéance de dette'), ('transfer_pending', 'Transfert en attente'), ('transfer_validated', 'Transfert validé'), ('payment_received', 'Paiement reçu'), ('payment_due', 'Paiement en retard'), ('invoice_created', 'Facture créée'), ('invoice_paid', 'Facture payée')], max_length=50, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('data', models.JSONField(blank=True, help_text='Informations supplémentaires (IDs, liens, etc.)', null=True, verbose_name='Données associées')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name="URL d'action")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_cb6908_idx')],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(choices=[('products', 'Produits'), ('services', 'Services'), ('inventory', 'Stock'), ('sales', 'Ventes'), ('customers', 'Clients'), ('suppliers', 'Fournisseurs'), ('cashbox', 'Caisse'), ('loans', 'Emprunts'), ('expenses', 'Dépenses'), ('analytics', 'Analytics'), ('settings', 'Paramètres'), ('users', 'Utilisateurs')], max_length=50, verbose_name='Module')),
                ('action', models.CharField(choices=[('view', 'Voir'), ('add', 'Ajouter'), ('change', 'Modifier'), ('delete', 'Supprimer'), ('export', 'Exporter'), ('approve', 'Approuver')], max_length=20, verbose_name='Action')),
                ('roles', models.ManyToManyField(blank=True, related_name='permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='accounts_us_employe_0cbd94_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_506163_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action', '-created_at'], name='accounts_us_action_cb5e15_idx'),
        ),
    ]
