# Generated by Django 5.2.7 on 2026-01-07 14:38

from django.db import migrations, models
from django_tenants.utils import get_public_schema_name, schema_context


def create_m2m_table(apps, schema_editor):
    """Créer la table ManyToMany uniquement dans les schémas tenants"""
    if schema_editor.connection.schema_name == get_public_schema_name():
        return  # Skip pour le schéma public
    
    # Exécuter le SQL pour créer la table ManyToMany
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS accounts_user_assigned_stores (
                id SERIAL PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE,
                store_id INTEGER NOT NULL REFERENCES inventory_store(id) ON DELETE CASCADE,
                UNIQUE(user_id, store_id)
            );
            CREATE INDEX IF NOT EXISTS accounts_user_assigned_stores_user_id_idx 
                ON accounts_user_assigned_stores(user_id);
            CREATE INDEX IF NOT EXISTS accounts_user_assigned_stores_store_id_idx 
                ON accounts_user_assigned_stores(store_id);
        """)


def drop_m2m_table(apps, schema_editor):
    """Supprimer la table ManyToMany"""
    if schema_editor.connection.schema_name == get_public_schema_name():
        return
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS accounts_user_assigned_stores CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_m2m_table, reverse_code=drop_m2m_table),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='assigned_stores',
                    field=models.ManyToManyField(
                        blank=True, 
                        related_name='assigned_users', 
                        to='inventory.store', 
                        verbose_name='Points de vente assignés'
                    ),
                ),
            ],
        ),
    ]
