# Generated by Django 5.2.7 on 2025-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_categories',
            field=models.BooleanField(default=False, verbose_name='Gérer les catégories'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_categories',
            field=models.BooleanField(default=False, verbose_name='Voir les catégories'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_inventory',
            field=models.BooleanField(default=False, verbose_name='Voir le stock'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_products',
            field=models.BooleanField(default=False, verbose_name='Voir les produits'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_services',
            field=models.BooleanField(default=False, verbose_name='Voir les services'),
        ),
    ]
