# Generated by Django 5.2.7 on 2026-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_bank',
            field=models.BooleanField(default=False, verbose_name='Gérer la banque'),
        ),
    ]
