# Generated by Django 5.2.7 on 2025-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_can_manage_categories_role_can_view_categories_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_user_ty_b6cfc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_custome_5b7e6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_supplie_6871ac_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer_company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer_credit_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer_payment_term',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer_tax_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_collaborator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_supplier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supplier_bank_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supplier_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supplier_company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supplier_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supplier_tax_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='collaborator', editable=False, max_length=20, verbose_name="Type d'utilisateur"),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
    ]
