# Generated by Django 5.2.7 on 2026-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_can_manage_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_mobile_money',
            field=models.BooleanField(default=False, verbose_name='Gérer MTN/Orange Money'),
        ),
    ]
