# Generated by Django 5.2.7 on 2025-12-17 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_accounts_us_user_ty_b6cfc8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('type', models.CharField(choices=[('stock_rupture', 'Rupture de stock'), ('stock_low', 'Stock faible'), ('debt_due', 'Échéance de dette'), ('transfer_pending', 'Transfert en attente'), ('transfer_validated', 'Transfert validé'), ('payment_received', 'Paiement reçu'), ('payment_due', 'Paiement en retard'), ('invoice_created', 'Facture créée'), ('invoice_paid', 'Facture payée')], max_length=50, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('data', models.JSONField(blank=True, help_text='Informations supplémentaires (IDs, liens, etc.)', null=True, verbose_name='Données associées')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name="URL d'action")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_cb6908_idx')],
            },
        ),
    ]
