# Generated by Django 5.2.7 on 2026-01-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('form_name', models.CharField(choices=[('product', 'Produit'), ('customer', 'Client'), ('supplier', 'Fournisseur'), ('sale', 'Vente'), ('invoice', 'Facture'), ('expense', 'Dépense')], max_length=50, verbose_name='Formulaire')),
                ('field_name', models.CharField(max_length=100, verbose_name='Nom du champ')),
                ('field_label', models.CharField(max_length=200, verbose_name='Libellé du champ')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Configuration de champ',
                'verbose_name_plural': 'Configurations de champs',
                'ordering': ['form_name', 'display_order', 'field_name'],
                'unique_together': {('form_name', 'field_name')},
            },
        ),
    ]
