# Generated by Django 5.2.7 on 2026-01-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconfiguration',
            name='form_name',
            field=models.CharField(choices=[('product', 'Produit'), ('product_table', 'Tableau Produit'), ('customer', 'Client'), ('supplier', 'Fournisseur'), ('sale', 'Vente'), ('invoice', 'Facture'), ('expense', 'Dépense')], max_length=50, verbose_name='Formulaire'),
        ),
    ]
