# Generated by Django 5.2.7 on 2026-01-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fieldconfiguration_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconfiguration',
            name='form_name',
            field=models.CharField(choices=[('product', 'Produit'), ('product_table', 'Tableau Produit'), ('service', 'Service'), ('service_table', 'Tableau Service'), ('purchase', 'Achat (Entrée Stock)'), ('purchase_table', 'Tableau Achat'), ('customer', 'Client'), ('supplier', 'Fournisseur'), ('sale', 'Vente'), ('invoice', 'Facture'), ('expense', 'Dépense')], max_length=50, verbose_name='Formulaire'),
        ),
    ]
