# Generated by Django 5.2.9 on 2025-12-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useractivity_user_alter_usersession_user'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='assigned_services', to='accounts.user', verbose_name='Personnel assigné'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par'),
        ),
        migrations.AlterField(
            model_name='serviceintervention',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='accounts.user', verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='serviceintervention',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='serviceintervention',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par'),
        ),
    ]
