# Generated by Django 5.2.7 on 2026-01-05 15:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashboxSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('opening_date', models.DateTimeField(verbose_name="Date d'ouverture")),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée')], default='open', max_length=20, verbose_name='Statut')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Solde d'ouverture")),
                ('expected_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde de fermeture attendu')),
                ('actual_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde de fermeture réel')),
                ('opening_notes', models.TextField(blank=True, verbose_name="Notes d'ouverture")),
                ('closing_notes', models.TextField(blank=True, verbose_name='Notes de fermeture')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-opening_date'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('count_type', models.CharField(choices=[('opening', 'Ouverture'), ('closing', 'Fermeture'), ('interim', 'Intermédiaire')], max_length=20, verbose_name='Type de comptage')),
                ('coins_10000', models.IntegerField(default=0, verbose_name='Pièces 10000 XAF')),
                ('coins_5000', models.IntegerField(default=0, verbose_name='Pièces 5000 XAF')),
                ('coins_2000', models.IntegerField(default=0, verbose_name='Pièces 2000 XAF')),
                ('coins_1000', models.IntegerField(default=0, verbose_name='Pièces 1000 XAF')),
                ('coins_500', models.IntegerField(default=0, verbose_name='Pièces 500 XAF')),
                ('coins_250', models.IntegerField(default=0, verbose_name='Pièces 250 XAF')),
                ('coins_200', models.IntegerField(default=0, verbose_name='Pièces 200 XAF')),
                ('coins_100', models.IntegerField(default=0, verbose_name='Pièces 100 XAF')),
                ('coins_50', models.IntegerField(default=0, verbose_name='Pièces 50 XAF')),
                ('coins_25', models.IntegerField(default=0, verbose_name='Pièces 25 XAF')),
                ('notes_10000', models.IntegerField(default=0, verbose_name='Billets 10000 XAF')),
                ('notes_5000', models.IntegerField(default=0, verbose_name='Billets 5000 XAF')),
                ('notes_2000', models.IntegerField(default=0, verbose_name='Billets 2000 XAF')),
                ('notes_1000', models.IntegerField(default=0, verbose_name='Billets 1000 XAF')),
                ('notes_500', models.IntegerField(default=0, verbose_name='Billets 500 XAF')),
            ],
            options={
                'verbose_name': 'Comptage de caisse',
                'verbose_name_plural': 'Comptages de caisse',
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('movement_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de mouvement')),
                ('movement_type', models.CharField(choices=[('in', 'Encaissement'), ('out', 'Décaissement')], max_length=10, verbose_name='Type de mouvement')),
                ('category', models.CharField(choices=[('sale', 'Vente'), ('customer_payment', 'Règlement client'), ('supplier_payment', 'Paiement fournisseur'), ('loan_repayment', 'Remboursement emprunt'), ('loan_disbursement', 'Décaissement emprunt'), ('expense', 'Dépense'), ('bank_deposit', 'Dépôt en banque'), ('bank_withdrawal', 'Retrait banque'), ('adjustment', 'Ajustement'), ('other', 'Autre')], max_length=30, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('check', 'Chèque'), ('bank_transfer', 'Virement')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde actuel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['store', 'name'],
            },
        ),
    ]
