# Generated by Django 5.2.7 on 2026-01-05 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashboxes', to='inventory.store', verbose_name='Point de vente'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='cashboxsession',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cashbox.cashbox', verbose_name='Caisse'),
        ),
        migrations.AddField(
            model_name='cashboxsession',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Caissier'),
        ),
        migrations.AddField(
            model_name='cashboxsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cashboxsession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='cashcount',
            name='cashbox_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='cashbox.cashboxsession', verbose_name='Session de caisse'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='cashbox_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cashbox.cashboxsession', verbose_name='Session de caisse'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='sales.sale', verbose_name='Vente'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
    ]
