# Generated by Django 5.2.7 on 2025-12-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
