# Generated by Django 5.2.7 on 2026-01-29 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='cashbox_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cashbox.cashboxsession', verbose_name='Session de caisse'),
        ),
    ]
