# Generated by Django 5.2.7 on 2026-01-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0003_alter_cashmovement_cashbox_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('bank_transfer', 'Virement'), ('mobile_money', 'Mobile Money (MTN/Orange)'), ('check', 'Chèque')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
