# Generated by Django 5.2.7 on 2025-10-14 03:08

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('email', models.EmailField(max_length=254, verbose_name='Email principal')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='starter', max_length=20, verbose_name="Plan d'abonnement")),
                ('max_users', models.IntegerField(default=3, verbose_name="Nombre max d'utilisateurs")),
                ('max_stores', models.IntegerField(default=1, verbose_name='Nombre max de points de vente')),
                ('max_products', models.IntegerField(default=1000, verbose_name='Nombre max de produits')),
                ('max_storage_mb', models.IntegerField(default=1000, verbose_name='Stockage max (MB)')),
                ('feature_services', models.BooleanField(default=False, verbose_name='Module Services')),
                ('feature_multi_store', models.BooleanField(default=False, verbose_name='Multi points de vente')),
                ('feature_loans', models.BooleanField(default=False, verbose_name='Gestion des emprunts')),
                ('feature_advanced_analytics', models.BooleanField(default=False, verbose_name='Analytics avancés')),
                ('feature_api_access', models.BooleanField(default=False, verbose_name='Accès API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name="Fin de période d'essai")),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.25, max_digits=5, verbose_name='Taux de TVA (%)')),
            ],
            options={
                'verbose_name': 'Société (Tenant)',
                'verbose_name_plural': 'Sociétés (Tenants)',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
            },
        ),
    ]
