# Generated by Django 5.2.7 on 2025-10-08 16:03

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('created_on', models.DateField(auto_now_add=True)),
                ('plan', models.CharField(default='Starter', max_length=50, verbose_name='Plan tarifaire')),
                ('max_users', models.IntegerField(default=3, verbose_name='Max. utilisateurs')),
                ('max_stores', models.IntegerField(default=1, verbose_name='Max. points de vente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name="Fin de période d'essai")),
                ('feature_services', models.BooleanField(default=False, verbose_name='Gestion des services')),
                ('feature_multi_store', models.BooleanField(default=False, verbose_name='Multi-points de vente')),
                ('feature_loans', models.BooleanField(default=False, verbose_name='Gestion des emprunts')),
                ('feature_advanced_analytics', models.BooleanField(default=False, verbose_name='Analytics avancées')),
                ('feature_api_access', models.BooleanField(default=False, verbose_name='Accès API')),
            ],
            options={
                'verbose_name': 'Société (Tenant)',
                'verbose_name_plural': 'Sociétés (Tenants)',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Domaine/Sous-domaine',
                'verbose_name_plural': 'Domaines/Sous-domaines',
            },
        ),
    ]
