# Generated by Django 5.2.7 on 2026-01-05 15:12

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('email', models.EmailField(max_length=254, verbose_name='Email principal')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='starter', max_length=20, verbose_name="Plan d'abonnement")),
                ('max_users', models.IntegerField(default=3, verbose_name="Nombre max d'utilisateurs")),
                ('max_stores', models.IntegerField(default=1, verbose_name='Nombre max de points de vente')),
                ('max_products', models.IntegerField(default=1000, verbose_name='Nombre max de produits')),
                ('max_storage_mb', models.IntegerField(default=1000, verbose_name='Stockage max (MB)')),
                ('feature_services', models.BooleanField(default=False, verbose_name='Module Services')),
                ('feature_multi_store', models.BooleanField(default=False, verbose_name='Multi points de vente')),
                ('feature_loans', models.BooleanField(default=False, verbose_name='Gestion des emprunts')),
                ('feature_advanced_analytics', models.BooleanField(default=False, verbose_name='Analytics avancés')),
                ('feature_api_access', models.BooleanField(default=False, verbose_name='Accès API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Suspendu')),
                ('suspension_reason', models.TextField(blank=True, null=True, verbose_name='Raison suspension')),
                ('provisioning_status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut du provisioning')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name="Fin de période d'essai")),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name="Fin d'abonnement")),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email facturation')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix mensuel')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Dernière facture')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Prochaine facturation')),
                ('storage_used_mb', models.IntegerField(default=0, verbose_name='Stockage utilisé (MB)')),
                ('last_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('total_users_count', models.IntegerField(default=0, verbose_name="Nombre d'utilisateurs")),
                ('total_products_count', models.IntegerField(default=0, verbose_name='Nombre de produits')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.25, max_digits=5, verbose_name='Taux de TVA (%)')),
            ],
            options={
                'verbose_name': 'Société (Tenant)',
                'verbose_name_plural': 'Sociétés (Tenants)',
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('total_tenants', models.IntegerField(default=0)),
                ('active_tenants', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_revenue_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_response_time_ms', models.IntegerField(default=0, verbose_name='Temps de réponse moyen (ms)')),
                ('error_rate_percent', models.FloatField(default=0, verbose_name="Taux d'erreur (%)")),
                ('total_storage_used_gb', models.FloatField(default=0, verbose_name='Stockage total utilisé (GB)')),
                ('peak_concurrent_users', models.IntegerField(default=0, verbose_name='Pic utilisateurs simultanés')),
            ],
            options={
                'verbose_name': 'Métriques système',
                'verbose_name_plural': 'Métriques système',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=150, verbose_name='Utilisateur admin')),
                ('action_type', models.CharField(max_length=50, verbose_name="Type d'action")),
                ('action_description', models.TextField(verbose_name='Description')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='Type de ressource')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID ressource')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.company')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro facture')),
                ('invoice_date', models.DateField(verbose_name='Date facture')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total TTC')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date paiement')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Méthode paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Facturation',
                'verbose_name_plural': 'Facturations',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro ticket')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('waiting_customer', 'En attente client'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=150, verbose_name='Assigné à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nom client')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Ticket support',
                'verbose_name_plural': 'Tickets support',
                'ordering': ['-created_at'],
            },
        ),
    ]
