# Generated by Django 5.2.7 on 2026-01-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_flexible_pricing',
            field=models.BooleanField(default=False, help_text='Si activé, le prix unitaire peut être modifié lors de la facturation. Sinon, le prix est verrouillé et tout surplus crée un solde restant.', verbose_name='Autoriser les prix flexibles en facturation'),
        ),
    ]
