# Generated by Django 5.2.7 on 2026-01-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_company_allow_flexible_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_warehouses',
            field=models.IntegerField(default=0, verbose_name='Nombre max de magasins/entrepôts'),
        ),
    ]
