# Generated by Django 5.2.7 on 2026-01-29 12:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_company_max_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='first_payment_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix pour la première inscription (ex: 229900 FCFA)', max_digits=10, verbose_name='Prix du 1er paiement (inscription)'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_first_payment',
            field=models.BooleanField(default=True, help_text="True si c'est la première inscription, False pour les renouvellements", verbose_name='Premier paiement'),
        ),
        migrations.AddField(
            model_name='company',
            name='renewal_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix pour les renouvellements après la première année (ex: 100000 FCFA)', max_digits=10, verbose_name='Prix de renouvellement'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_duration_days',
            field=models.IntegerField(default=365, help_text="Nombre de jours pour chaque période d'abonnement (ex: 365 pour 1 an)", verbose_name="Durée de l'abonnement (jours)"),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_days',
            field=models.IntegerField(default=14, help_text="Nombre de jours d'essai gratuit à l'inscription (ex: 14)", verbose_name="Jours d'essai gratuit"),
        ),
    ]
