# Generated by Django 5.2.8 on 2025-11-27 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('order_date', models.DateField(verbose_name='Date de commande')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Livraison prévue')),
                ('actual_delivery', models.DateField(blank=True, null=True, verbose_name='Livraison réelle')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('confirmed', 'Confirmé'), ('received', 'Reçu'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.store', verbose_name='Magasin de destination')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.25, max_digits=5, verbose_name='Taux TVA (%)')),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité reçue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produit')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='suppliers.purchaseorder', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('supplier_code', models.CharField(max_length=50, unique=True, verbose_name='Code fournisseur')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Contact principal')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Numéro fiscal')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Compte bancaire')),
                ('payment_term', models.CharField(choices=[('immediate', 'Comptant'), ('15_days', '15 jours'), ('30_days', '30 jours'), ('60_days', '60 jours'), ('90_days', '90 jours')], default='30_days', max_length=20, verbose_name='Conditions de paiement')),
                ('rating', models.IntegerField(blank=True, help_text='Note de 1 à 5', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Évaluation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de paiement')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='suppliers.purchaseorder', verbose_name='Bon de commande')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='suppliers.supplier', verbose_name='Fournisseur')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseurs',
                'ordering': ['-payment_date'],
            },
        ),
    ]
