# Generated by Django 5.2.7 on 2025-12-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant déjà versé au fournisseur pour cette commande', max_digits=12, verbose_name='Montant payé'),
        ),
    ]
