# Generated by Django 5.2.9 on 2025-12-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
    ]
