# Generated by Django 5.2.7 on 2025-12-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='suppliers.purchaseorder', verbose_name='Bon de commande'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='accounts.user', verbose_name='Reçu par'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_transfers', to='accounts.user', verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer', verbose_name='Transfert'),
        ),
        migrations.AddField(
            model_name='store',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to='accounts.user', verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_transfers', to='inventory.store', verbose_name='Magasin destination'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.store', verbose_name='Magasin source'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.store', verbose_name='Magasin destination'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.store', verbose_name='Magasin'),
        ),
        migrations.AddField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.store', verbose_name='Magasin'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.store', verbose_name='Magasin'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryline',
            unique_together={('inventory', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'store')},
        ),
    ]
