# Generated by Django 5.2.7 on 2025-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='receipt_number',
            field=models.CharField(blank=True, help_text="Numéro de la pièce d'entrée en stock", max_length=50, verbose_name='Numéro de pièce'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence du bon de livraison ou facture', max_length=100, verbose_name='Référence document'),
        ),
    ]
