# Generated by Django 5.2.7 on 2026-01-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='receipt_number',
            field=models.CharField(blank=True, help_text="Numéro de la pièce d'entrée en stock (un bon peut contenir plusieurs produits)", max_length=50, null=True, verbose_name='Numéro de pièce'),
        ),
    ]
