# Generated by Django 5.2.9 on 2025-12-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_created_by_and_more'),
        ('suppliers', '0003_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='suppliers.purchaseorder', verbose_name='Bon de commande'),
        ),
    ]
