# Generated by Django 5.2.7 on 2025-12-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_receipt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.IntegerField(default=0, verbose_name='Dernier numéro utilisé')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Séquence de numéros de pièce',
                'verbose_name_plural': 'Séquences de numéros de pièce',
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
