# Generated by Django 5.2.7 on 2026-01-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='date',
            field=models.DateField(blank=True, help_text='Date à laquelle le mouvement de stock a été réalisé (peut être différente de la date de saisie)', null=True, verbose_name='Date de réalisation'),
        ),
    ]
