# Generated by Django 5.2.7 on 2026-01-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_reference_to_stock_transfer'),
        ('inventory', '0004_add_date_field'),
    ]

    operations = [
    ]
