# Generated by Django 5.2.7 on 2025-12-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_is_active_to_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total de la facture (peut différer de unit_cost * quantity)', max_digits=12, null=True, verbose_name='Montant de la facture'),
        ),
    ]
