# Generated by Django 5.2.7 on 2025-12-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='receipt_number',
            field=models.CharField(blank=True, help_text="Numéro de la pièce d'entrée en stock", max_length=50, null=True, unique=True, verbose_name='Numéro de pièce'),
        ),
    ]
