# Generated by Django 5.2.7 on 2025-12-13 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_make_receipt_number_unique'),
        ('invoicing', '0005_invoiceline_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='invoicing.invoice', verbose_name='Facture'),
        ),
    ]
