# Generated by Django 5.2.7 on 2025-12-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockmovement_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total de la ligne (avec taxes) pour les ventes/factures', max_digits=12, null=True, verbose_name='Montant total'),
        ),
    ]
