# Generated by Django 5.2.7 on 2025-12-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_make_receipt_number_unique'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicepayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Paiement de facture', 'verbose_name_plural': 'Paiements de facture'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.store', verbose_name='Point de vente'),
            preserve_default=False,
        ),
    ]
