# Generated by Django 5.2.7 on 2026-01-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='status',
            field=models.CharField(choices=[('success', 'Réussi'), ('failed', 'Échoué'), ('pending', 'En attente')], default='success', max_length=20, verbose_name='Statut'),
        ),
    ]
