# Generated by Django 5.2.7 on 2025-12-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_invoiceline_product'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='services.service', verbose_name='Service'),
        ),
    ]
