# Generated by Django 5.2.8 on 2025-11-27 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('loan_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de prêt')),
                ('loan_type', models.CharField(choices=[('bank', 'Prêt bancaire'), ('supplier', 'Crédit fournisseur'), ('personal', 'Prêt personnel'), ('other', 'Autre')], max_length=20, verbose_name='Type de prêt')),
                ('lender_name', models.CharField(max_length=200, verbose_name='Nom du prêteur')),
                ('lender_contact', models.CharField(blank=True, max_length=200, verbose_name='Contact prêteur')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant emprunté')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'intérêt (%)")),
                ('duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (mois)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('paid', 'Remboursé'), ('defaulted', 'En défaut'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total (capital + intérêts)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé')),
                ('purpose', models.TextField(blank=True, verbose_name='Objet du prêt')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de paiement')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant capital')),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant intérêts')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.user', verbose_name='Créé par')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='loans.loan', verbose_name='Emprunt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='accounts.user', verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Paiement d'emprunt",
                'verbose_name_plural': "Paiements d'emprunts",
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('installment_number', models.IntegerField(verbose_name="Numéro d'échéance")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant capital')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant intérêts')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé')),
                ('status', models.CharField(choices=[('pending', 'À payer'), ('paid', 'Payé'), ('overdue', 'En retard'), ('partial', 'Partiellement payé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='loans.loan', verbose_name='Emprunt')),
            ],
            options={
                'verbose_name': "Échéancier d'emprunt",
                'verbose_name_plural': "Échéanciers d'emprunts",
                'ordering': ['loan', 'installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
