# Generated by Django 5.2.7 on 2026-01-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money (MTN/Orange)'), ('check', 'Chèque')], max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
