# Generated by Django 5.2.7 on 2026-01-05 15:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('company_name', models.CharField(default='SG-STOCK', max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_slogan', models.CharField(blank=True, default='Solution de Gestion Commerciale', max_length=200, verbose_name='Slogan')),
                ('company_email', models.EmailField(default='contact@sgstock.cm', max_length=254, verbose_name='Email')),
                ('company_phone', models.CharField(default='+237 XXX XXX XXX', max_length=50, verbose_name='Téléphone')),
                ('company_address', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('company_website', models.URLField(blank=True, verbose_name='Site web')),
                ('tax_id', models.CharField(blank=True, max_length=100, verbose_name='Numéro fiscal / RC')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name="Logo de l'entreprise")),
                ('primary_color', models.CharField(default='#0769CF', help_text='Couleur principale (format: #RRGGBB)', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#003FD8', help_text='Couleur secondaire (format: #RRGGBB)', max_length=7, verbose_name='Couleur secondaire')),
                ('text_color', models.CharField(default='#292D32', help_text='Couleur du texte (format: #RRGGBB)', max_length=7, verbose_name='Couleur du texte')),
                ('invoice_header_text', models.TextField(blank=True, help_text="Texte personnalisé pour l'en-tête de facture", verbose_name="Texte d'en-tête")),
                ('show_logo_on_invoice', models.BooleanField(default=True, verbose_name='Afficher le logo sur la facture')),
                ('invoice_footer_text', models.TextField(default='Merci pour votre confiance !', verbose_name='Message de pied de page')),
                ('invoice_footer_note', models.TextField(blank=True, help_text='Note additionnelle en bas de facture', verbose_name='Note additionnelle')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Nom de la banque')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='Numéro de compte bancaire')),
                ('mobile_money_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro Mobile Money')),
                ('invoice_prefix', models.CharField(default='FAC', max_length=10, verbose_name='Préfixe de facture')),
                ('show_tax_breakdown', models.BooleanField(default=True, verbose_name='Afficher le détail de la TVA')),
                ('default_payment_terms', models.TextField(default='Règlement à réception de facture', verbose_name='Conditions de paiement par défaut')),
            ],
            options={
                'verbose_name': "Configuration d'entreprise",
                'verbose_name_plural': "Configurations d'entreprise",
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='public_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='public_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
