# Generated by Django 5.2.7 on 2025-12-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('company_name', models.CharField(default='SG-STOCK', max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_slogan', models.CharField(blank=True, default='Solution de Gestion Commerciale', max_length=200, verbose_name='Slogan')),
                ('company_email', models.EmailField(default='contact@sgstock.cm', max_length=254, verbose_name='Email')),
                ('company_phone', models.CharField(default='+237 XXX XXX XXX', max_length=50, verbose_name='Téléphone')),
                ('company_address', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('company_website', models.URLField(blank=True, verbose_name='Site web')),
                ('tax_id', models.CharField(blank=True, max_length=100, verbose_name='Numéro fiscal / RC')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name="Logo de l'entreprise")),
                ('primary_color', models.CharField(default='#0769CF', help_text='Couleur principale (format: #RRGGBB)', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#003FD8', help_text='Couleur secondaire (format: #RRGGBB)', max_length=7, verbose_name='Couleur secondaire')),
                ('text_color', models.CharField(default='#292D32', help_text='Couleur du texte (format: #RRGGBB)', max_length=7, verbose_name='Couleur du texte')),
                ('invoice_header_text', models.TextField(blank=True, help_text="Texte personnalisé pour l'en-tête de facture", verbose_name="Texte d'en-tête")),
                ('show_logo_on_invoice', models.BooleanField(default=True, verbose_name='Afficher le logo sur la facture')),
                ('invoice_footer_text', models.TextField(default='Merci pour votre confiance !', verbose_name='Message de pied de page')),
                ('invoice_footer_note', models.TextField(blank=True, help_text='Note additionnelle en bas de facture', verbose_name='Note additionnelle')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Nom de la banque')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='Numéro de compte bancaire')),
                ('mobile_money_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro Mobile Money')),
                ('invoice_prefix', models.CharField(default='FAC', max_length=10, verbose_name='Préfixe de facture')),
                ('show_tax_breakdown', models.BooleanField(default=True, verbose_name='Afficher le détail de la TVA')),
                ('default_payment_terms', models.TextField(default='Règlement à réception de facture', verbose_name='Conditions de paiement par défaut')),
            ],
            options={
                'verbose_name': "Configuration d'entreprise",
                'verbose_name_plural': "Configurations d'entreprise",
            },
        ),
    ]
