# Generated by Django 5.2.7 on 2025-12-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
