# Generated by Django 5.2.7 on 2026-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='beneficiary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
