# Generated by Django 5.2.7 on 2026-01-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_beneficiary_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money (MTN/Orange)'), ('check', 'Chèque')], max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
    ]
